spring:
  port: ${port:80}
  thymeleaf:
    cache: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/mytinycalendar
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

