spring:
  thymeleaf:
    cache: false
  profile:
    active: dev
  jpa.hibernate.ddl-auto: update

spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: c:/tmp/bookmark
    username: sa
    password:
  jpa.database: H2

spring:
  profiles: heroku
  datasource:
    driverClassName: org.postgresql.Driver
  jpa.database: POSTGRESQL
